// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/xcursion.h"
#include <Rcpp.h>

using namespace Rcpp;

// two_by_two_rarray
xt::rarray<double> two_by_two_rarray();
RcppExport SEXP _xcursion_two_by_two_rarray() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(two_by_two_rarray());
    return rcpp_result_gen;
END_RCPP
}
// two_by_two_rtensor
xt::rtensor<double, 2> two_by_two_rtensor();
RcppExport SEXP _xcursion_two_by_two_rtensor() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(two_by_two_rtensor());
    return rcpp_result_gen;
END_RCPP
}
// plus_one
xt::rarray<double> plus_one(xt::rarray<double> x);
RcppExport SEXP _xcursion_plus_one(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< xt::rarray<double> >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(plus_one(x));
    return rcpp_result_gen;
END_RCPP
}
// xt_sum
xt::rarray<double> xt_sum(xt::rarray<double> x, xt::rarray<double> y);
RcppExport SEXP _xcursion_xt_sum(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< xt::rarray<double> >::type x(xSEXP);
    Rcpp::traits::input_parameter< xt::rarray<double> >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(xt_sum(x, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_xcursion_two_by_two_rarray", (DL_FUNC) &_xcursion_two_by_two_rarray, 0},
    {"_xcursion_two_by_two_rtensor", (DL_FUNC) &_xcursion_two_by_two_rtensor, 0},
    {"_xcursion_plus_one", (DL_FUNC) &_xcursion_plus_one, 1},
    {"_xcursion_xt_sum", (DL_FUNC) &_xcursion_xt_sum, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_xcursion(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
