# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a simple two by two matrix with a rarray
#'
#' @export
two_by_two_rarray <- function() {
    .Call(`_xcursion_two_by_two_rarray`)
}

#' Create a simple two by two matrix with a rtensor
#' @export
two_by_two_rtensor <- function() {
    .Call(`_xcursion_two_by_two_rtensor`)
}

#' Take in an R object, and add 1 to it
#'
#' @param x A numeric R object
#'
#' @export
plus_one <- function(x) {
    .Call(`_xcursion_plus_one`, x)
}

#' Broadcast sum
#'
#' @param x,y Numeric vectors, matrices, or arrays
#'
#' @export
xt_sum <- function(x, y) {
    .Call(`_xcursion_xt_sum`, x, y)
}

xt_dim <- function(x) {
    .Call(`_xcursion_xt_dim`, x)
}

xt_shape_ex <- function() {
    .Call(`_xcursion_xt_shape_ex`)
}

