# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
two_by_two_rarray <- function() {
    .Call(`_xcursion_two_by_two_rarray`)
}

#' @export
two_by_two_rtensor <- function() {
    .Call(`_xcursion_two_by_two_rtensor`)
}

#' @export
plus_one <- function(x) {
    .Call(`_xcursion_plus_one`, x)
}

